name: florescophotography
favicon: null
layout_spectrum: 0.92373
typography_spectrum: 0.32864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7cdd4'
    - '#000000'
    - '#6a83b9'
    - '#004b8f'
    - '#784711'
  brandStrength: 0.47942291642539203
  lightness: 0.625
  saturation: 0.22117720893584192
  rhythmicContrast: 0.04991110973060131
purpose: []
