name: floresco photography
favicon: null
layout_spectrum: 0.22174
typography_spectrum: 0.32864
title: Floresco Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebd0c5'
    - '#5c6ea1'
    - '#2f2c3c'
    - '#d7a5b2'
    - '#090707'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.04991110973060131
purpose: []
